version: '2'

networks:
  marbles:

services:

  marbles_org1:
    image: $IMAGE_NAME
    extends:
      file: base.yaml
      service: marbles_org
    environment:
      - creds_filename=marbles_tls_org1.json
    volumes:
        - ../crypto-config:/marbles/config/crypto-config
        - ./.hfc-key-store/org1:/root/.hfc-key-store
        - ./.hfc-key-store/org1:/marbles/config/crypto/kvs
    ports:
      - 3001:3001
    networks:
      - marbles

  marbles_org2:
    image: $IMAGE_NAME
    extends:
      file: base.yaml
      service: marbles_org
    environment:
      - creds_filename=marbles_tls_org2.json
    volumes:
        - ../crypto-config:/marbles/config/crypto-config
        - ./.hfc-key-store/org2:/root/.hfc-key-store
        - ./.hfc-key-store/org2:/marbles/config/crypto/kvs
    ports:
      - 3002:3001
    networks:
      - marbles

  marbles_org3:
    image: $IMAGE_NAME
    extends:
      file: base.yaml
      service: marbles_org
    environment:
      - creds_filename=marbles_tls_org3.json
    volumes:
        - ../crypto-config:/marbles/config/crypto-config
        - ./.hfc-key-store/org3:/root/.hfc-key-store
        - ./.hfc-key-store/org3:/marbles/config/crypto/kvs
    ports:
      - 3003:3001
    networks:
      - marbles
    networks:
      - marbles
